/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Gwappa (https://sketchfab.com/Gwappa)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/lantern-utrecht-1890b4a77b794c6d9db9d2450255422d
title: Lantern Utrecht
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        pCube8_lambert1_0: THREE.Mesh
        Lantern_lambert1_0: THREE.Mesh
        pCylinder4_lambert1_0: THREE.Mesh
        pCube10_lambert1_0: THREE.Mesh
        pCube7_lambert1_0: THREE.Mesh
        pCube9_lambert1_0: THREE.Mesh
    }
    materials: {
        lambert1: THREE.MeshStandardMaterial
    }
}

export default function LanternModel({
    ...props
}: JSX.IntrinsicElements['group']) {
    const group = useRef<THREE.Group>()
    const { nodes, materials } = useGLTF(
        '/models/lanternModel.gltf'
    ) as GLTFResult
    return (
        <group ref={group} {...props} dispose={null} scale={4}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <group scale={5}>
                        <group rotation={[0, Math.PI / 2, 0]}>
                            <mesh
                                geometry={nodes.pCube8_lambert1_0.geometry}
                                material={materials.lambert1}
                            />
                        </group>
                        <group position={[0, 1, 0]}>
                            <mesh
                                geometry={nodes.Lantern_lambert1_0.geometry}
                                material={materials.lambert1}
                            />
                        </group>
                        <group
                            position={[0, 12.27, 0]}
                            scale={[0.61, 0.05, 0.61]}
                        >
                            <mesh
                                geometry={nodes.pCylinder4_lambert1_0.geometry}
                                material={materials.lambert1}
                            />
                        </group>
                        <group rotation={[-Math.PI, 0, -Math.PI]}>
                            <mesh
                                geometry={nodes.pCube10_lambert1_0.geometry}
                                material={materials.lambert1}
                            />
                        </group>
                        <group rotation={[0, -Math.PI / 2, 0]}>
                            <mesh
                                geometry={nodes.pCube7_lambert1_0.geometry}
                                material={materials.lambert1}
                            />
                        </group>
                        <mesh
                            geometry={nodes.pCube9_lambert1_0.geometry}
                            material={materials.lambert1}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/lanternModel.gltf')
