import Head from 'next/head'
import { ReactNode, Suspense } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import {
    EffectComposer,
    Bloom,
    ChromaticAberration,
    DepthOfField
} from '@react-three/postprocessing'
import { BlendFunction } from 'postprocessing'
import {
    CubeCamera,
    Environment,
    OrbitControls,
    PerspectiveCamera
} from '@react-three/drei'

import styles from '../styles/car.module.css'
import { Ground } from '../components/CarShow/Ground'
import AlternativeCorvetteModel from '../components/CarShow/CorvetteModel/alternative'
import { Rings } from '../components/CarShow/Rings'
import { Boxes } from '../components/CarShow/Boxes'
import { FloatingGrid } from '../components/CarShow/FloatingGrid'
import { Vector2 } from 'three'

function CarShow() {
    return (
        <>
            {/* Possibilita movimentar a camera a partir de um ponto fixo */}
            {/* target: ponto fixo */}
            <OrbitControls target={[0, 0.35, 0]} maxPolarAngle={1.45} />

            <PerspectiveCamera makeDefault fov={50} position={[3, 2, 5]} />

            <color args={[0, 0, 0]} attach="background" />

            {/* Forma para renderizar o carro fora dos outros para aplicar a sombra */}
            <CubeCamera resolution={256} frames={Infinity}>
                {/* @ts-ignore: Unreachable code error */}
                {tex =>
                    (
                        <>
                            <Environment map={tex} />
                            <AlternativeCorvetteModel />
                        </>
                    ) as ReactNode
                }
            </CubeCamera>

            <Rings />
            <Boxes />
            <FloatingGrid />

            <spotLight
                color={[1, 0.25, 0.7]}
                intensity={1.5}
                angle={0.6}
                penumbra={0.5}
                position={[5, 5, 0]}
                castShadow
                shadow-bias={-0.0001}
            />

            <spotLight
                color={[0.14, 0.5, 1]}
                intensity={2}
                angle={0.6}
                penumbra={0.5}
                position={[-5, 5, 0]}
                castShadow
                shadow-bias={-0.0001}
            />

            <Ground />

            <EffectComposer>
                {/* <DepthOfField
                    focusDistance={0.0035}
                    focalLength={0.01}
                    bokehScale={3}
                    height={480}
                /> */}
                <Bloom
                    blendFunction={BlendFunction.ADD}
                    intensity={1.3}
                    width={300} // render width
                    height={300} // render height
                    kernelSize={5} // blur kernel size
                    luminanceThreshold={0.15} // Raise this value to mask out darker elements in the scene
                    luminanceSmoothing={0.025} // smoothness of the luminance threshold. Range is [0, 1]
                />
                <ChromaticAberration
                    blendFunction={BlendFunction.NORMAL} // blend mode
                    offset={new Vector2(0.0005, 0.0012)} // color offset
                />
            </EffectComposer>
        </>
    )
}

export default function CarShowPage() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Car Show</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Suspense fallback={null}>
                <Canvas shadows>
                    {/* Todo o show */}
                    <CarShow />
                </Canvas>
            </Suspense>
        </div>
    )
}
