import Head from "next/head";
import { Suspense } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

import styles from "../styles/Home.module.css";
import { Box } from "../components/Box";
import { AnimatedSphere } from "../components/AnimatedSphere";
import { AnyaModel } from "../components/AnyaModel";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React With Three.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Checar a documentação para mais detalhes */}
      <h1>Box Geometry and textures</h1>
      <Canvas className={styles.canvas}>
        <OrbitControls enableZoom={false} />
        <ambientLight intensity={0.5} />
        <directionalLight position={[-2, 5, 2]} intensity={1} />
        <Suspense fallback="fallback...">
          {/* position={[x, y, z]} */}
          <Box position={[-4, 0, -4]} />
          <Box materialType="texture" />
          <Box position={[4, 0, -4]} materialType="normal" />
        </Suspense>
      </Canvas>

      <h1>3D Model</h1>

      <Canvas className={styles.canvas}>
        <OrbitControls enableZoom={false} />
        <ambientLight intensity={0.5} />
        <directionalLight position={[-2, 5, 2]} intensity={1} />
        <Suspense fallback="fallback...">
          <AnyaModel position={[0, -3, 0]} />
        </Suspense>
      </Canvas>

      <h1>Blob animated</h1>

      <Canvas className={styles.canvas}>
        <OrbitControls enableZoom={false} />
        <ambientLight intensity={0.5} />
        <directionalLight position={[-2, 5, 2]} intensity={1} />
        <Suspense fallback="fallback...">
          <AnimatedSphere />
        </Suspense>
      </Canvas>
    </div>
  );
}
